volumes:
  db-data:
  cache-store:
  sockets:
services:
  web:
    environment:
      - APP_HOST=${APP_HOST:-localhost}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE:-dummy}
      - DATABASE_USERNAME=${DATABASE_USERNAME:-postgres}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-postgres}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/1}
      - FORCE_SSL=${FORCE_SSL:-false}
      - ENABLE_BASIC_AUTH=${ENABLE_BASIC_AUTH:-false}
      - STORAGE_SERVICE=${STORAGE_SERVICE:-local}
      - AWS_REGION=${AWS_REGION}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
    build:
      context: .
      target: web
    volumes:
      - type: volume
        source: db-data
        target: /rails/tmp/db/postgres_data
        volume:
          nocopy: true
      - type: volume
        source: cache-store
        target: /rails/tmp/data/redis
        volume:
          nocopy: true
      - type: volume
        source: sockets
        target: /rails/tmp/sockets
        volume:
          nocopy: true
    depends_on:
      - db
      - redis
  nginx:
    environment:
      - VPC_CIDR=${VPC_CIDR:-10.0.0.0/16}
    build:
      context: .
    volumes:
      - type: volume
        source: sockets
        target: /var/run/sockets
        volume:
          nocopy: true
    depends_on:
      - web
    ports:
      - ${PORT:-3000}:80
    develop:
      watch:
        - action: sync+restart
          path: ./nginx/nginx.conf
          target: /etc/nginx/nginx.conf
        - action: sync+restart
          path: ./nginx/default.conf
          target: /etc/nginx/templates/default.conf.template
  db:
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-postgres}
    image: postgres:16.6-alpine
    ports:
      - 5432:5432
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
  redis:
    image: redis:8.0.2-alpine
    ports:
      - 6379:6379
    volumes:
      - type: volume
        source: cache-store
        target: /data
        volume:
          nocopy: true
networks:
  default:
    ipam:
      config:
        - subnet: ${VPC_CIDR:-10.0.0.0/16}
