en:
  meta:
    title: Demo Site
    default:
      description: Demo site for portfolio
      keywords: ''
    account:
      feed:
        page_name: Feed
        description: Displays the latest posts from users you follow
      posts:
        page_name: Posts
        description: Displays a list of posts
      followings:
        page_name: Following
        description: Displays a list of users you follow
      followers:
        page_name: Followers
        description: Displays a list of your followers
      profile:
        page_name: Profile
        description: Displays your profile
      register_info:
        page_name: Registration Info
        description: Displays your registration information
      app_settings:
        page_name: Settings
        description: Displays your settings
    users:
      id:
        page_name: "%{user_name}'s Posts"
        description: Displays a list of posts by %{user_name}
        posts:
          page_name: "%{user_name}'s Posts"
          description: Displays a list of posts by %{user_name}
        followings:
          page_name: "%{user_name}'s Following"
          description: Displays a list of users %{user_name} follows
        followers:
          page_name: "%{user_name}'s Followers"
          description: Displays a list of %{user_name}'s followers
      sign_in:
        page_name: Sign In
        description: Sign in to your account
      sign_up:
        page_name: Sign Up
        description: Create a new account
