ja:
  meta:
    default:
      title: Demo site
      description: Demo site for portfolio
    account:
      feed:
        title: フィード
        description: あなたがフォローしているユーザーの最新の投稿を表示します
      posts:
        title: 投稿一覧
        description: 投稿一覧を表示します
      followings:
        title: フォロー中
        description: フォロー中のユーザー一覧を表示します
      followers:
        title: フォロワー
        description: フォロワー一覧を表示します
      profile:
        title: プロフィール
        description: プロフィールを表示します
      register_info:
        title: 登録情報
        description: 登録情報を表示します
      app_settings:
        title: 設定
        description: 設定を表示します
    users:
      title: '%{user_name}さんの投稿一覧'
      description: '%{user_name}さんの投稿一覧を表示します'
      posts:
        title: '%{user_name}さんの投稿一覧'
        description: '%{user_name}さんの投稿一覧を表示します'
      followings:
        title: '%{user_name}さんのフォロー中'
        description: '%{user_name}さんのフォロー中のユーザー一覧を表示します'
      followers:
        title: '%{user_name}さんのフォロワー'
        description: '%{user_name}さんのフォロワー一覧を表示します'
      sign_in:
        title: ログイン
        description: アカウントにログインします
      sign_up:
        title: アカウント登録
        description: 新しいアカウントを作成します
