en:
  generic:
    back: Back
    back_to_home: Back to home
    back_to_index: Back to index
    cancel: Cancel
    change: Change
    close: Close
    continue: Continue
    create: Create
    cut_out: Cut out
    date: Date
    delete: Delete
    description: Description
    edit: Edit
    home: Home
    image: Image
    name: Name
    next: Next
    other: Other
    post: Post
    publish: Publish
    published: Published
    register: Registration
    registration: Registration
    reload: Reload
    reply: Reply
    save: Save
    search: Search
    select_image: Select image
    send: Send
    show_detail: Show detail
    size: Size
    sort: Sort
    submit: Submit
    terms_of_service: Terms of service
    update: Update
    url: URL
  user:
    posts: Posts
    follow: Follow
    unfollow: Unfollow
    follower: Follower
    following: Following
    account:
      avatar_image: Avatar image
      feed: Feed
      profile: Profile
      register_info: Register info
      app_settings: Setting
    auth:
      login: Sign in
      logout: Sign out
      signup: Sign up
      with_provider:
        sign_in: Sign in with %{name}
        sign_up: Sign up with %{name}
      delete_provider: 'Disconnect %{provider} account'
      already_have_account: Already have an account?
      not_registered_yet: Not registered yet?
      forgot_your_password: Forgot your password?
      didn_t_receive_confirmation_instructions: Didn't receive confirmation instructions?
      didn_t_receive_unlock_instructions: Didn't receive unlock instructions?
      current_password: Current password
      new_password: New password
      send_me_reset_password_instructions: Send me reset password instructions
      resend_confirmation_instructions: Resend confirmation instructions
      resend_unlock_instructions: Resend unlock instructions
      delete: Delete account
      placeholder:
        password: Half-width alphanumeric characters %{count} or more
      modal:
        delete:
          title: Are you sure you want to delete your account?
          body: All data will be deleted
          enter: Delete
  post:
    placeholder: write something
    modal:
      delete:
        title: Are you sure you want to delete this post?
        body: Once deleted, it cannot be undone
        enter: Delete
  dropzone:
    drop: Drop %{item}
    select_or_drag_and_drop: Drag 'n' drop %{item}
