name: deploy

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Choose log level'
        required: true
        default: 'info'
        type: choice
        options:
          - info
          - debug
      environment:
        description: 'Choose environment'
        required: true
        default: 'production'
        type: choice
        options:
          - production

env:
  AWS_REGION: ap-northeast-1
  APP_ID: portfolio-social_post-${{ github.event.inputs.environment }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
          role-duration-seconds: 1800
        
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ env.APP_ID }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker compose -p $REPOSITORY build web nginx
          docker tag $REPOSITORY-web:latest $REGISTRY/$REPOSITORY-web:$IMAGE_TAG
          docker tag $REPOSITORY-nginx:latest $REGISTRY/$REPOSITORY-nginx:$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY-web:$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY-nginx:$IMAGE_TAG

